server:
  port: 8080
  servlet:
    context-path:

spring:
  # thymeleaf
  thymeleaf:
    cache: false

  # jpa
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

# 日志
logging:
  file:
    name: log/bbs.log
  #  level:
  #    root: warn
  #    org.springframework.web: debug
  #    org.hibernate: error
  logback:
    rollingpolicy:
      max-file-size: 5MB

# 自定义bbs
bbs:
  path:
    domain:
      http://localhost:8080
    upload:
      j:/upload


