server:
  port: 8080

spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs
    username: root
    password: root

  # thymeleaf
  thymeleaf:
    cache: false

  # jpa
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  # 邮箱
  mail:
    host: smtp.exmail.qq.com
    protocol: smtps
    port: 465
    nickname: Tragoedia.cn
    username: account@tragoedia.cn
    password: Hyxadjlsksk1999
    properties:
      mail:
        smtp:
          ssl:
            enable: true

## Mybatis
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.tragoedia.bbs.entity
#  configuration:
#    use-generated-keys: true # 自动生成主键
#    map-underscore-to-camel-case: true # 下划线转驼峰

# 日志
logging:
  file:
    name: D:/bbs.log
  level:
    root: warn
    org.springframework.web: debug
    org.hibernate: error
  logback:
    rollingpolicy:
      max-file-size: 5MB
