server:
  port: 8080
  servlet:
    context-path:

spring:
  # thymeleaf
  thymeleaf:
    cache: false

  # jpa
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
## Mybatis
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.tragoedia.bbs.entity
#  configuration:
#    use-generated-keys: true # 自动生成主键
#    map-underscore-to-camel-case: true # 下划线转驼峰

# 日志
logging:
  file:
    name: D:/bbs.log
  #  level:
  #    root: warn
  #    org.springframework.web: debug
  #    org.hibernate: error
  logback:
    rollingpolicy:
      max-file-size: 5MB

# 自定义bbs
bbs:
  path:
    domain:
      http://localhost:8080
